steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
   
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/watchful-net-455704-i0/kub-java/kub-java',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: [
      'push',
      'us-central1-docker.pkg.dev/watchful-net-455704-i0/kub-java/kub-java'
    ]

images:
  - us-central1-docker.pkg.dev/watchful-net-455704-i0/kub-java/kub-java

logsBucket: gs://build-logs-watchful-1/

options:
  logging: GCS_ONLY

