apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml

images:
  - name: kub-java
    newName: us-central1-docker.pkg.dev/inductive-gift-456306-h4/kub-java/kub-java